### ISSUE TITLE
Failed to activate the atom-psql package in windows

### ISSUE THREAD

**Issue by RoyceSamuel** [maisk/atom-psql#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [atom-psql](https://github.com/maisk/atom-psql) package 0.20.0

### Stack Trace

Failed to activate the atom-psql package

```
At ENOENT: no such file or directory, open 'C:\tmp\atom-psql-errors.log'

Error: ENOENT: no such file or directory, open 'C:\tmp\atom-psql-errors.log'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at /packages/atom-psql/lib/atom-psql-controller.js:170:21)
    at Object.activate (/packages/atom-psql/lib/atom-psql.js:33:23)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:690:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.22.1/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:646:50)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/atom-environment.js:854:36
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-clock 0.1.15 
atom-psql 0.20.0 
atom-python-run 0.9.5 
language-pgsql 0.2.3 
python-indent 1.1.4 
python-tools 0.6.9 
tool-bar 1.1.0 
```

**Comment by maisk** [comment]
For the moment windows is not supported. Sorry.
