### ISSUE TITLE
path must be a string or Buffer

### ISSUE THREAD

**Issue by victor987** [maisk/atom-psql#2]
Ubuntu 17.10

"Failed to activate the atom-psql package" message when opening atom.

```
TypeError: path must be a string or Buffer
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at new AtomPsqlController (/home/victor/.atom/packages/atom-psql/lib/atom-psql-controller.js:170:21)
    at Object.activate (/home/victor/.atom/packages/atom-psql/lib/atom-psql.js:33:23)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:253:25)
    at /usr/share/atom/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at /usr/share/atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:690:42)
    at config.transactAsync (/usr/share/atom/resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:646:50)
    at /usr/share/atom/resources/app/src/atom-environment.js:854:36
```

**Comment by maisk** [comment]
I cannot understand how this error appear.
if you can, try the latest version and inform me if still exists.
Thanks

**Comment by victor987** [comment]
It works now with version 0.26.0.
Thank you
