### ISSUE TITLE
Python 3.6 screws up "gyp" a dependency blocking install

### ISSUE THREAD

**Issue by MattOates** [maisk/atom-psql#5]
On macOS High Sierra at least /usr/bin/python is 2.7 but my local environment is setup to use a more recent version of Python in my home. Looks like there is a --python option to ensure the system Python gets used. Not sure how to do this manually within the Atom node environment. But if atom-psql can set that path it might be worth doing.

```
Installing “atom-psql@0.27.0” failed.

> node-pty@0.6.10 install /private/var/folders/yg/03gqlxpx05j3jq3t5klpp0bh0000gn/T/apm-install-dir-118220-15364-1w8nbx3.4t8wfusor/node_modules/atom-psql/node_modules/node-pty
> node scripts/install.js

/private/var/folders/yg/03gqlxpx05j3jq3t5klpp0bh0000gn/T/apm-install-dir-118220-15364-1w8nbx3.4t8wfusor
`-- (empty)


gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/yg/03gqlxpx05j3jq3t5klpp0bh0000gn/T/apm-install-dir-118220-15364-1w8nbx3.4t8wfusor/node_modules/atom-psql/node_modules/node-pty
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/yg/03gqlxpx05j3jq3t5klpp0bh0000gn/T/apm-install-dir-118220-15364-1w8nbx3.4t8wfusor/package.json'
npm WARN apm-install-dir-118220-15364-1w8nbx3.4t8wfusor No description
npm WARN apm-install-dir-118220-15364-1w8nbx3.4t8wfusor No repository field.
npm WARN apm-install-dir-118220-15364-1w8nbx3.4t8wfusor No README data
npm WARN apm-install-dir-118220-15364-1w8nbx3.4t8wfusor No license field.
npm ERR! Darwin 17.4.0
npm ERR! argv "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/matt/.atom/.apm/.apmrc" "--userconfig" "/Users/matt/.atom/.apmrc" "install" "/private/var/folders/yg/03gqlxpx05j3jq3t5klpp0bh0000gn/T/d-118220-15364-1nybuyp.bo3whfr/package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-pty@0.6.10 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-pty@0.6.10 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-pty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-pty
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-pty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/yg/03gqlxpx05j3jq3t5klpp0bh0000gn/T/apm-install-dir-118220-15364-1w8nbx3.4t8wfusor/npm-debug.log
npm ERR! code 1
```

**Comment by MattOates** [comment]
Ok looks like really not your problem https://github.com/atom/atom/issues/7450 :(
